---
- name: Configure Talos Cluster
  hosts: localhost
  connection: local
  gather_facts: false
  environment: "{{ proxy_env | default({}) }}"
  roles:
    - role: talos_setup
      when: proxmox_talos_servers