---
- name: Check OS version, upgrade, and reboot
  hosts: all
  become: yes

  tasks:
    - name: Get OS distribution
      ansible.builtin.setup:
        filter: ansible_distribution

    - name: Get OS version
      ansible.builtin.setup:
        filter: ansible_distribution_version

    - name: Display OS information
      ansible.builtin.debug:
        msg: "OS: {{ ansible_distribution }}, Version: {{ ansible_distribution_version }}"

    - name: Upgrade all packages (DNF)
      ansible.builtin.dnf:
        name: "*"
        state: latest
      when: ansible_pkg_mgr == 'dnf'

    - name: Upgrade all packages (APT)
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes
      when: ansible_pkg_mgr == 'apt'

    - name: Upgrade all packages (Zypper)
      community.general.zypper:
        name: "*"
        state: latest
        type: package
      when: ansible_pkg_mgr == 'zypper'

    - name: Reboot the system
      ansible.builtin.reboot:

    - name: Wait for system to become reachable
      ansible.builtin.wait_for_connection:
        delay: 60
        timeout: 300

    - name: Display new OS version
      ansible.builtin.debug:
        msg: "Updated OS version: {{ ansible_distribution_version }}"