# roles/pinepods/tasks/main.yml
---
- name: Create a directory for temporary files if it does not exist
  ansible.builtin.file:
    path: /tmp/k3s
    state: directory
    mode: '0755'

- name: Ensure pinepods namespace exists
  kubernetes.core.k8s:
    kind: Namespace
    name: "{{ pinepods_namespace }}"
    state: present
    kubeconfig: "{{ kubeconfig }}"
  run_once: true

- name: Create Pinepods values file
  template:
    src: pinepods-values.yaml.j2
    dest: "/tmp/k3s/pinepods-values.yaml"
    mode: '0600'
  run_once: true

- name: Display Pinepods values file contents
  ansible.builtin.command:
    cmd: cat /tmp/k3s/pinepods-values.yaml
  register: pinepods_values_content
  run_once: true

- name: Show Pinepods values file contents
  debug:
    var: pinepods_values_content.stdout_lines
  run_once: true

# - name: Deploy Pinepods using Helm
#   kubernetes.core.helm:
#     name: "{{ pinepods_release_name }}"
#     chart_ref: ~/Documents/github/PinePods/deployment/kubernetes/helm/pinepods  # Assuming chart is in local directory
#     release_namespace: "{{ pinepods_namespace }}"
#     values_files:
#       - "/tmp/k3s/pinepods-values.yaml"
#     kubeconfig: "{{ kubeconfig }}"
#   run_once: true


# Force deploy
- name: Deploy Pinepods using Helm
  kubernetes.core.helm:
    name: "{{ pinepods_release_name }}"
    chart_ref: ~/Documents/github/PinePods/deployment/kubernetes/helm/pinepods
    release_namespace: "{{ pinepods_namespace }}"
    values_files:
      - "/tmp/k3s/pinepods-values.yaml"
    kubeconfig: "{{ kubeconfig }}"
    force: true
    atomic: true
    wait: true
    values:
      podpeople:
        forceRecreate: true
  run_once: true