---
argument_specs:
  main:
    short_description: Setup Talos k8s servers
    options:
      apiserver_endpoint:
        description: Virtual ip-address configured on the control plane
        required: true
      kube_vip_arp:
        description: Enables ARP broadcasts from Leader
        default: true
        type: bool
      kube_vip_iface:
        description:
          - Explicitly define an interface that ALL control nodes
          - should use to propagate the VIP, define it here.
          - Otherwise, kube-vip will determine the right interface
          - automatically at runtime.
        default: ~
      kube_vip_tag_version:
        description: Image tag for kube-vip
        default: v0.7.2
      kube_vip_cloud_provider_tag_version:
        description: Tag for kube-vip-cloud-provider manifest when enabled
        default: main
      kube_vip_lb_ip_range:
        description: IP range for kube-vip load balancer
        default: ~
      metal_lb_controller_tag_version:
        description: Image tag for MetalLB
        default: v0.14.3