---
- name: Create namespace
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: testing-pinepods

- name: Create External Service
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: "pinepods-external"
        namespace: testing-pinepods
      spec:
        type: ExternalName
        externalName: "{{ external_pinepods_service_host }}"
        ports:
          - port: "{{ external_pinepods_service_port }}"
            targetPort: "{{ external_pinepods_service_port }}"
            protocol: TCP

- name: Create Ingress
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: "pinepods-ingress"
        namespace: testing-pinepods
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
          traefik.ingress.kubernetes.io/router.tls: "true"
          traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
          # Optional: Add if you need to modify how the proxy works
          # traefik.ingress.kubernetes.io/router.middlewares: "{{ app_namespace }}-strip-prefix@kubernetescrd"
      spec:
        rules:
          - host: "{{ pinepods_app_hostname }}"
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: "pinepods-external"
                      port:
                        number: "{{ external_pinepods_service_port }}"